name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Ngrok İndiriliyor!
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Ngrok Arşivden Çıkarılıyor!
      run: Expand-Archive ngrok.zip
    - name: Token İşleniyor!
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: TS Etkinleştiriliyor!
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: RDP için Güvenlik Duvarı Aktif!
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Regdit'ten RDP Mülküne İzin Veriliyor!
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Kullanıcı Atanıyor!
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Windows2019" -Force)
    - name: Tünel Oluşturuluyor!
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Zaman Aşımı Komut Dosyasını İndiriliyor!
      run: Invoke-WebRequest https://raw.githubusercontent.com/shieldwhite/timeout/WhiteShield/timeout.ps1 -OutFile timeout.ps1
    - name: Max 6 Saat Açık
      run: ./timeout.ps1
