name: CI

on: workflow_dispatch
name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Ngrok ve NSSM'yi indiriyor!
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/Windows2019RDP-US/main/Files/nssm.exe -OutFile nssm.exe
    - name: NSSM & Ngrok'u Windows Dizinine kopyalanıyor!
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: NGROK hesabınızı bağlayın
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Önemli Dosyaları İndirin.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/Windows2019RDP-US/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/Windows2019RDP-US/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Emre37destan/Windows2019RDP-US/main/Files/loop.bat -OutFile loop.bat
    - name: NGROK için YML dosyası oluşturun.
      run: start NGROK-US.bat
    - name: RDP Erişimini etkinleştirin.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tünel Oluşturun
      run: sc start ngrok
    - name: RDP 2core-7GB Ram'inize bağlanın.
      run: cmd /c NGROK-CHECK.bat
    - name: Hepsi tamam! Şimdi Tab'ı kapatabilirsiniz! Maksimum sanal makine süresi: 6 saat.
      run: cmd /c loop.bat
      
    
